---

# This example doesn't cover tests against the actually built packages.

name: PyPA sampleproject tested over declared interpreters

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  FORCE_COLOR: "1" # Make tools pretty.

jobs:
  build-package:
    name: Build & verify package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: pypa/sampleproject
          path: sampleproject
      - uses: actions/checkout@v4
        with:
          path: action
      - uses: ./action
        id: baipp
        with:
          path: sampleproject

  test-package:
    needs: build-package
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.build-package.outputs.supported_pythons_job_matrix_value)}}

    steps:
      - uses: actions/setup-python@v4
      - uses: actions/checkout@v4
        with:
          repository: pypa/sampleproject
      - run: python -m unittest tests/

...